# Python Programming

This is a Jupyter notebook. We use Jupyter to demonstrate Python code in class. You will also submit the codes from your homework as a notebook. Each cell is either a "Code" cell or a "Markdown" cell (like this one, which contains text).

## Variable Types

Numerical variable types include integer, float, and complex.  It's important to use the variable type that makes sense for your application.  You can use **int()**, **float()**, and **complex()** to switch between the different types.  First we convert an integer to a float and a complex.

In [12]:
a=5# assign value of 5 (integer) to variable
print(a)
print(float(a))
print(complex(a))

5
5.0
(5+0j)


If we convert a float to an integer, it removes the fractional part, keeping the digits to the left of the decimal.

In [17]:
a=4.7
print(a)
print(int(a))

a=-4.7
print(a)
print(int(a))

4.7
4
-4.7
-4


  You cannot convert a complex to a float (or an integer).

In [14]:
a=4.7+2.6j
print(a)
print(float(a))

(4.7+2.6j)


TypeError: can't convert complex to float

Words or groups of words are saved as *strings*.  A number can be converted to a string using the **str()** function.  Strings cannot be converted to numbers unless the formatting is correct. 

In [34]:
str(5)

'5'

In [35]:
str(2.+8.j)

'(2+8j)'

In [36]:
int('89')

89

In [37]:
float('-35.8')

-35.8

In [38]:
complex('(-2+3j)')

(-2+3j)

## Arithmetic

Arithmetic is straightforward.  For mixed variable types, floats win over integers and complexi (or complexes) win over floats.

In [39]:
a=4
b=-4.2
c=2.9-8.6j
print(a+b)# integer-float
print(c**b)# float-complex
print(c/a)# integer-complex

-0.20000000000000018
(4.7027703507567416e-05-8.23322955604603e-05j)
(0.725-2.15j)


Float division always give a float and gives the result that we normally call *division*.

In [43]:
print(5./2.5)
print(9/3)
print(6/4)

2.0
3.0
1.5


Integer division obeys variable type rules while removing remainders.  Specifically, when normal division does not equal a whole number, it reduces the numerator until it finds a number that does with the corresponding whole number being the result. This gives disparate results for positive and negative numbers.

In [48]:
print(5.//2.5)
print(6.//2.5)
print(9//3)
print(6//4)
print(-6//4)

2.0
2.0
3
1
-2


Modulo gives the remainder.  Note the behavior for negative numbers.

In [49]:
print(6%2)
print(4.5%2.5)
print(-8%5)

0
2.0
2


Strings have an addition function, where the two strings are concatenated.  To add a numeral to a string, the numeral has to be converted to a string before concatenated.

In [40]:
a='basket'
b='ball'
c=5
print(a+b)
print(b+str(c))
print(b+c)

basketball
ball5


TypeError: can only concatenate str (not "int") to str

Here are some examples of increments.

In [50]:
q=6.5
print(q)
q+=1
print(q)
q/=2.5
print(q)
q**=3
print(q)
r='bar'
s='stool'
r+=s
print(r)
r+=s
print(r)

6.5
7.5
3.0
27.0
barstool
barstoolstool


## Lists & Arrays

Lists are groupings of values that can be a mix of types.  Here is an example.

In [52]:
drs=[3,4.5,'orange',9/4]
print(drs[0])
c=3
print(drs[2])
print(drs[c])
print(drs[:])
print(drs[1:3])

3
orange
2.25
[3, 4.5, 'orange', 2.25]
[4.5, 'orange']


[-1] always refers to the last entry. [-2] refers to the next-to-last entry, and so forth.

In [54]:
print(drs)
print(drs[-1])
print(drs[-3])

[3, 4.5, 'orange', 2.25]
2.25
4.5


Some fun operations.

In [55]:
print(len(drs)) # Length of list
print(drs+[4]) # Add an entry
print(drs*4)

4
[3, 4.5, 'orange', 2.25, 4]
[3, 4.5, 'orange', 2.25, 3, 4.5, 'orange', 2.25, 3, 4.5, 'orange', 2.25, 3, 4.5, 'orange', 2.25]


Arrays are like lists, but the entries must all be of the same numerical type.  They are provided using the *numpy* package.

In [59]:
import numpy as np # load numpy package with alias np
x=np.array([3.,5.,-9.])
print(x*3)
print(x**2)

[  9.  15. -27.]
[ 9. 25. 81.]


Many arrays are built from the zero array, the one array, and range array.  The default type is float, but you can declare them as other numeric types.

In [65]:
print(np.zeros(5))
print(np.zeros(5,int))
print(np.ones(4))
print(np.ones(4,complex)*3)
print(np.arange(3,10))
print(np.arange(3.4,10.8))

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[1. 1. 1. 1.]
[3.+0.j 3.+0.j 3.+0.j 3.+0.j]
[3 4 5 6 7 8 9]
[ 3.4  4.4  5.4  6.4  7.4  8.4  9.4 10.4]


Here are some operations between arrays.

In [76]:
x=np.array([3.,5.,-9.])
y=2*np.arange(3.)
print('x =',x)
print('y =',y)
print('sum =',x+y)# addition
print('x^y =',x**y)# power
print('dot product =',x.dot(y))# dot product
print('cross product =',np.cross(x,y))

x = [ 3.  5. -9.]
y = [0. 2. 4.]
sum = [ 3.  7. -5.]
x^y = [1.000e+00 2.500e+01 6.561e+03]
dot product = -26.0
cross product = [ 38. -12.   6.]


Numpy also provides multidimensional arrays.

In [83]:
w=np.array([[3,9,45],[-15,-4,-15]])
print('w =',w)
print('w[1] =',w[1])
print('w[:,2] =',w[:,2])
print('nrows,ncols =',np.shape(w))

w = [[  3   9  45]
 [-15  -4 -15]]
w[1] = [-15  -4 -15]
w[:,2] = [ 45 -15]
nrows,ncols = (2, 3)


Use **numpy.vstack** to add a row.

In [84]:
u=np.vstack((w,[-4,8,3]))
print(u)

[[  3   9  45]
 [-15  -4 -15]
 [ -4   8   3]]


Here are some operations.

In [85]:
print(5*u)

[[ 15  45 225]
 [-75 -20 -75]
 [-20  40  15]]


In [89]:
print(np.zeros((3,3))+1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [90]:
print(u+1)

[[  4  10  46]
 [-14  -3 -14]
 [ -3   9   4]]


In [86]:
np.linalg.det(u)# determinant

-4850.999999999996

In [87]:
np.linalg.inv(u)# inverse

array([[-0.02226345, -0.06864564, -0.00927644],
       [-0.02164502, -0.03896104,  0.12987013],
       [ 0.02803546,  0.01236858, -0.0253556 ]])

In [88]:
u.T# transpose

array([[  3, -15,  -4],
       [  9,  -4,   8],
       [ 45, -15,   3]])

Broadcasting examples.  The first example obeys rules, while the second example does not.

In [97]:
print('u =',u)
s=np.array([5,9,-3])
print('s =',s)
print('shape(u) =',np.shape(u))
print('shape(s) =',np.shape(s))
print('u+s =',u+s)# = sum_j (u_ij+s_j)

u = [[  3   9  45]
 [-15  -4 -15]
 [ -4   8   3]]
s = [ 5  9 -3]
shape(u) = (3, 3)
shape(s) = (3,)
u+s = [[  8  18  42]
 [-10   5 -18]
 [  1  17   0]]


In [95]:
r=w.T
print('r =',r)
s=np.array([5,9,-3])
print('s =',s)
print('shape(r) =',np.shape(r))
print('shape(s) =',np.shape(s))
print('r+s =',r+s)# = sum_j (r_ij+s_j)

r = [[  3 -15]
 [  9  -4]
 [ 45 -15]]
s = [ 5  9 -3]
shape(r) = (3, 2)
shape(s) = (3,)


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

## Control Statements

In class we introduce the *for loop*, the *if statement*, and the *while loop*.  Here's a simple for loop.

In [99]:
for i in np.arange(5):
    print(2*i)

0
2
4
6
8


You can use this to do a sum.

In [101]:
tot=0 # initialize sum
for i in np.arange(5):
    tot+=2*i
print(tot)

20


However, using universal functions, or ufuncs, are much faster.

In [105]:
import time
start=time.time()# initial time
tot=0
for i in np.arange(10000000):
    tot+=2*i
print(tot)
end=time.time()
print(end-start,'sec')

99999990000000
5.18737530708313 sec


In [106]:
import time
start=time.time()# initial time
tot=np.sum(2*np.arange(10000000))
print(tot)
end=time.time()
print(end-start,'sec')

99999990000000
0.03638410568237305 sec


That's 140x faster!  This adds up for long calculations, and it can be the difference between a minute and a few hours.

For the next two control statements you need *conditionals*, which compare values.  Here is an example.

In [112]:
for i in np.arange(6):
    print(i,i%3==0)

0 True
1 False
2 False
3 True
4 False
5 False


Here is an example of an *if statement*, where we consider for a velocity function $v(t)=-2+7t-5t^2$ for $t=0-2$ whether an object is going left or right at each timestep.

In [138]:
t=0.1*np.arange(20)
v=-2.+7*t-5.*t**2 # v(t)
d=np.zeros(3,int)# number in that direction
#[right,left,center]
for i in np.arange(20):
    if v[i]>0.:
        d[0]+=1
    elif v[i]<0.:
        d[1]+=1
    else:
        d[2]+=1
print('# right =',d[0])
print('# left =',d[1])
print('# still =',d[2])

# right = 6
# left = 13
# still = 1


A *while statement* repeats until the conditional is not satisfied.  In this example, we use a while statement to find how long it takes a ball that is thrown vertically in the air takes to hit the ground.

In [149]:
g=-9.8#m/s^2 - acceleration due to gravity
v0=5.#m/s - initial velocity
t=0#s - initialize time
dt=0.1#s - time step
t+=dt
d=v0*t+g*t**2# equation for distance d(t)
while d>0.:
    t+=dt
    d=v0*t+g*t**2
print('ground time =',t,'sec')
t_theo = -v0/g
print('theory =',t_theo,'sec')
print('error fraction =',(t-t_theo)/t_theo)

ground time = 0.6 sec
theory = 0.5102040816326531 sec
error fraction = 0.17599999999999993


How can we improve this program?

What happens if you make an error, perhaps use the wrong sign for $g$?  The ball would keep accelerating upward and never stop -- causing an infinite loop.  A *break* statement would allow the loop to finish at some point.

In [150]:
g=9.8#m/s^2 - error
v0=5.
t=0
dt=0.1
t+=dt
d=v0*t+g*t**2
nstep=1# count number of steps
maxstep=1000000
while d>0.:
    t+=dt
    d=v0*t+g*t**2
    nstep+=1
    if nstep>maxstep:
        print('More than a million steps.')
        print('tmax =',t,'sec')
        print('Increase step size or check the acceleration')
        break
if nstep<=maxstep:#stop from printing if maxstep is reached
    print('ground time =',t,'sec')
    t_theo = -v0/g
    print('theory =',t_theo,'sec')
    print('error fraction =',(t-t_theo)/t_theo)

More than a million steps.
tmax = 100000.10000133289 sec
Increase step size or check the acceleration


## User-Defined Function

User-defined functions allow you to have modularity in your code.  Let's take the routine from the last example and make it a function.

In [153]:
def ground_time(v0,dt=0.1,maxstep=1000000):# set a default value
#for the time step and max number of steps
    g=-9.8#m/s^2 - acceleration due to gravity
    t=0#s - initialize time
    t+=dt
    d=v0*t+g*t**2# equation for distance d(t)
    nstep=1# count number of steps
    while d>0.:
        t+=dt
        d=v0*t+g*t**2
        nstep+=1
        if nstep>maxstep:
            print('More than',maxstep,'steps.')
            print('tmax =',t,'sec')
            print('Increase step size or maxstep, or check the acceleration')
            break
    if nstep<=maxstep:#stop from printing if maxstep is reached
        print('ground time =',t,'sec')
        t_theo = -v0/g
        print('theory =',t_theo,'sec')
        print('error fraction =',(t-t_theo)/t_theo)

In [154]:
ground_time(5.)#example from before

ground time = 0.6 sec
theory = 0.5102040816326531 sec
error fraction = 0.17599999999999993


In [155]:
ground_time(15.)# try a different v0

ground time = 1.6000000000000003 sec
theory = 1.530612244897959 sec
error fraction = 0.045333333333333586


In [156]:
ground_time(15.,dt=0.01)#increase precision

ground time = 1.5400000000000011 sec
theory = 1.530612244897959 sec
error fraction = 0.006133333333334132


Questions:
- Why should the parameters dt and maxstep have defaults?
- What is another way you can hit maxstep?